name: Deploy

on: push

jobs:
  firts_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print variable
        run: echo "${{ secrets.TOKEN_SECRET}}"   
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          node-version: '18'

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Instalar dependencias
        run: npm install